# /used ai for this

biology_questions = [
    {"question": "What is the powerhouse of the cell?", "options": ["A. Nucleus", "B. Mitochondria", "C. Ribosome", "D. Golgi Body"], "answer": "B"},
    {"question": "What is the basic unit of life?", "options": ["A. Tissue", "B. Organ", "C. Cell", "D. Molecule"], "answer": "C"},
    {"question": "Which part of the cell controls its activities?", "options": ["A. Cytoplasm", "B. Nucleus", "C. Cell Membrane", "D. Vacuole"], "answer": "B"},
    {"question": "What is the green pigment in plants called?", "options": ["A. Carotene", "B. Chlorophyll", "C. Xanthophyll", "D. Anthocyanin"], "answer": "B"},
    {"question": "What process do plants use to make their own food?", "options": ["A. Respiration", "B. Photosynthesis", "C. Transpiration", "D. Digestion"], "answer": "B"},
    {"question": "What gas do plants absorb during photosynthesis?", "options": ["A. Oxygen", "B. Nitrogen", "C. Carbon Dioxide", "D. Hydrogen"], "answer": "C"},
    {"question": "What gas do plants release during photosynthesis?", "options": ["A. Oxygen", "B. Carbon Dioxide", "C. Nitrogen", "D. Hydrogen"], "answer": "A"},
    {"question": "What is the process by which plants lose water called?", "options": ["A. Respiration", "B. Transpiration", "C. Photosynthesis", "D. Excretion"], "answer": "B"},
    {"question": "What is the largest organ in the human body?", "options": ["A. Liver", "B. Brain", "C. Skin", "D. Heart"], "answer": "C"},
    {"question": "How many chambers does the human heart have?", "options": ["A. 2", "B. 3", "C. 4", "D. 5"], "answer": "C"},
    {"question": "What is the normal human body temperature (in Fahrenheit)?", "options": ["A. 96.8°F", "B. 98.6°F", "C. 100.4°F", "D. 94.6°F"], "answer": "B"},
    {"question": "How many bones are there in the adult human body?", "options": ["A. 196", "B. 206", "C. 216", "D. 226"], "answer": "B"},
    {"question": "Which blood cells help fight infections?", "options": ["A. Red Blood Cells", "B. White Blood Cells", "C. Platelets", "D. Plasma"], "answer": "B"},
    {"question": "Which blood cells carry oxygen throughout the body?", "options": ["A. Red Blood Cells", "B. White Blood Cells", "C. Platelets", "D. Plasma"], "answer": "A"},
    {"question": "What is responsible for blood clotting?", "options": ["A. Red Blood Cells", "B. White Blood Cells", "C. Platelets", "D. Plasma"], "answer": "C"},
    {"question": "What is the universal blood donor group?", "options": ["A. A", "B. B", "C. AB", "D. O negative"], "answer": "D"},
    {"question": "What is the universal blood recipient group?", "options": ["A. A", "B. B", "C. AB", "D. O"], "answer": "C"},
    {"question": "Which organ purifies blood in the human body?", "options": ["A. Liver", "B. Kidney", "C. Heart", "D. Lungs"], "answer": "B"},
    {"question": "Which organ pumps blood in the human body?", "options": ["A. Liver", "B. Kidney", "C. Heart", "D. Lungs"], "answer": "C"},
    {"question": "What is the functional unit of the kidney called?", "options": ["A. Neuron", "B. Nephron", "C. Alveoli", "D. Villi"], "answer": "B"},
    {"question": "What is the functional unit of the nervous system called?", "options": ["A. Neuron", "B. Nephron", "C. Alveoli", "D. Axon"], "answer": "A"},
    {"question": "Which organ is responsible for gaseous exchange in humans?", "options": ["A. Heart", "B. Lungs", "C. Liver", "D. Kidney"], "answer": "B"},
    {"question": "What is the process of cell division for growth called?", "options": ["A. Meiosis", "B. Mitosis", "C. Fusion", "D. Fission"], "answer": "B"},
    {"question": "What is the process of cell division that produces gametes called?", "options": ["A. Meiosis", "B. Mitosis", "C. Fusion", "D. Fission"], "answer": "A"},
    {"question": "What is DNA short for?", "options": ["A. Deoxyribonucleic Acid", "B. Dinitrogen Acid", "C. Diribonucleic Acid", "D. Deoxyribose Acid"], "answer": "A"},
    {"question": "Who discovered the structure of DNA?", "options": ["A. Darwin", "B. Watson and Crick", "C. Mendel", "D. Pasteur"], "answer": "B"},
    {"question": "Who is known as the father of genetics?", "options": ["A. Charles Darwin", "B. Gregor Mendel", "C. James Watson", "D. Louis Pasteur"], "answer": "B"},
    {"question": "Who proposed the theory of evolution by natural selection?", "options": ["A. Charles Darwin", "B. Gregor Mendel", "C. James Watson", "D. Louis Pasteur"], "answer": "A"},
    {"question": "What is the study of living organisms called?", "options": ["A. Physics", "B. Chemistry", "C. Biology", "D. Geology"], "answer": "C"},
    {"question": "What is the study of plants called?", "options": ["A. Zoology", "B. Botany", "C. Ecology", "D. Genetics"], "answer": "B"},
    {"question": "What is the study of animals called?", "options": ["A. Zoology", "B. Botany", "C. Ecology", "D. Genetics"], "answer": "A"},
    {"question": "What is the study of heredity called?", "options": ["A. Zoology", "B. Botany", "C. Genetics", "D. Ecology"], "answer": "C"},
    {"question": "What are organisms that make their own food called?", "options": ["A. Autotrophs", "B. Heterotrophs", "C. Saprophytes", "D. Parasites"], "answer": "A"},
    {"question": "What are organisms that depend on others for food called?", "options": ["A. Autotrophs", "B. Heterotrophs", "C. Producers", "D. None of these"], "answer": "B"},
    {"question": "What is the site of protein synthesis in a cell?", "options": ["A. Nucleus", "B. Mitochondria", "C. Ribosome", "D. Golgi Body"], "answer": "C"},
    {"question": "Which organelle is known as the 'suicide bag' of the cell?", "options": ["A. Lysosome", "B. Ribosome", "C. Vacuole", "D. Plastid"], "answer": "A"},
    {"question": "Which part of the plant conducts photosynthesis mainly?", "options": ["A. Root", "B. Stem", "C. Leaf", "D. Flower"], "answer": "C"},
    {"question": "Which vitamin is produced when skin is exposed to sunlight?", "options": ["A. Vitamin A", "B. Vitamin C", "C. Vitamin D", "D. Vitamin K"], "answer": "C"},
    {"question": "Deficiency of Vitamin C causes which disease?", "options": ["A. Rickets", "B. Scurvy", "C. Night Blindness", "D. Beriberi"], "answer": "B"},
    {"question": "Deficiency of Vitamin D causes which disease?", "options": ["A. Rickets", "B. Scurvy", "C. Night Blindness", "D. Beriberi"], "answer": "A"},
    {"question": "What is the process by which organisms maintain a stable internal environment called?", "options": ["A. Metabolism", "B. Homeostasis", "C. Osmosis", "D. Respiration"], "answer": "B"},
    {"question": "What is the movement of water molecules through a semi-permeable membrane called?", "options": ["A. Diffusion", "B. Osmosis", "C. Transpiration", "D. Filtration"], "answer": "B"},
    {"question": "How many pairs of chromosomes are there in a human cell?", "options": ["A. 22", "B. 23", "C. 24", "D. 46"], "answer": "B"},
    {"question": "What is the total number of chromosomes in a human cell?", "options": ["A. 23", "B. 44", "C. 46", "D. 48"], "answer": "C"},
    {"question": "Which gland is known as the master gland of the human body?", "options": ["A. Thyroid", "B. Pituitary", "C. Adrenal", "D. Pancreas"], "answer": "B"},
    {"question": "Which hormone regulates blood sugar levels?", "options": ["A. Insulin", "B. Adrenaline", "C. Thyroxine", "D. Estrogen"], "answer": "A"},
    {"question": "Which organ produces insulin?", "options": ["A. Liver", "B. Pancreas", "C. Kidney", "D. Spleen"], "answer": "B"},
    {"question": "What is the term for animals that eat only plants?", "options": ["A. Carnivores", "B. Herbivores", "C. Omnivores", "D. Insectivores"], "answer": "B"},
    {"question": "What is the term for animals that eat only meat?", "options": ["A. Carnivores", "B. Herbivores", "C. Omnivores", "D. Decomposers"], "answer": "A"},
    {"question": "What is the process by which a caterpillar becomes a butterfly called?", "options": ["A. Fertilization", "B. Metamorphosis", "C. Pollination", "D. Germination"], "answer": "B"},
]

