# /used ai for this


chemistry_questions = [
    {"question": "What is the chemical symbol for Gold?", "options": ["A. Ag", "B. Au", "C. Gd", "D. Go"], "answer": "B"},
    {"question": "What is the chemical symbol for Silver?", "options": ["A. Ag", "B. Au", "C. Si", "D. Sv"], "answer": "A"},
    {"question": "What is the chemical symbol for Sodium?", "options": ["A. So", "B. Sd", "C. Na", "D. Nd"], "answer": "C"},
    {"question": "What is the chemical symbol for Potassium?", "options": ["A. Po", "B. K", "C. Pt", "D. Pm"], "answer": "B"},
    {"question": "What is the chemical symbol for Iron?", "options": ["A. Ir", "B. Fe", "C. In", "D. I"], "answer": "B"},
    {"question": "What is the chemical symbol for Lead?", "options": ["A. Ld", "B. Le", "C. Pb", "D. Pl"], "answer": "C"},
    {"question": "What is the chemical symbol for Tin?", "options": ["A. Ti", "B. Tn", "C. Sn", "D. Ta"], "answer": "C"},
    {"question": "What is the chemical symbol for Copper?", "options": ["A. Co", "B. Cu", "C. Cp", "D. Cr"], "answer": "B"},
    {"question": "What is the chemical symbol for Mercury?", "options": ["A. Me", "B. Mc", "C. Hg", "D. Hy"], "answer": "C"},
    {"question": "What is the atomic number of Hydrogen?", "options": ["A. 0", "B. 1", "C. 2", "D. 3"], "answer": "B"},
    {"question": "What is the atomic number of Oxygen?", "options": ["A. 6", "B. 7", "C. 8", "D. 9"], "answer": "C"},
    {"question": "What is the atomic number of Carbon?", "options": ["A. 5", "B. 6", "C. 7", "D. 8"], "answer": "B"},
    {"question": "What is the most abundant gas in Earth's atmosphere?", "options": ["A. Oxygen", "B. Carbon Dioxide", "C. Nitrogen", "D. Hydrogen"], "answer": "C"},
    {"question": "What is the chemical formula for water?", "options": ["A. H2O", "B. HO2", "C. H2O2", "D. OH"], "answer": "A"},
    {"question": "What is the chemical formula for table salt?", "options": ["A. NaCl", "B. KCl", "C. CaCl2", "D. NaOH"], "answer": "A"},
    {"question": "What is the chemical formula for carbon dioxide?", "options": ["A. CO", "B. CO2", "C. C2O", "D. CO3"], "answer": "B"},
    {"question": "What is the pH value of a neutral solution?", "options": ["A. 0", "B. 7", "C. 14", "D. 10"], "answer": "B"},
    {"question": "What is the pH range of an acidic solution?", "options": ["A. 0-7", "B. 7-14", "C. Exactly 7", "D. Above 14"], "answer": "A"},
    {"question": "What is the pH range of a basic solution?", "options": ["A. 0-7", "B. 7-14", "C. Exactly 0", "D. Below 0"], "answer": "B"},
    {"question": "Who is known as the father of the Periodic Table?", "options": ["A. Antoine Lavoisier", "B. Dmitri Mendeleev", "C. John Dalton", "D. Niels Bohr"], "answer": "B"},
    {"question": "How many elements are there in the modern Periodic Table?", "options": ["A. 108", "B. 118", "C. 128", "D. 98"], "answer": "B"},
    {"question": "What is the lightest element in the Periodic Table?", "options": ["A. Helium", "B. Hydrogen", "C. Lithium", "D. Oxygen"], "answer": "B"},
    {"question": "What is the most electronegative element?", "options": ["A. Oxygen", "B. Chlorine", "C. Fluorine", "D. Nitrogen"], "answer": "C"},
    {"question": "Which gas is commonly known as laughing gas?", "options": ["A. Nitrous Oxide", "B. Carbon Monoxide", "C. Methane", "D. Ozone"], "answer": "A"},
    {"question": "What is the process of a solid turning into a liquid called?", "options": ["A. Evaporation", "B. Melting", "C. Sublimation", "D. Condensation"], "answer": "B"},
    {"question": "What is the process of a gas turning into a liquid called?", "options": ["A. Evaporation", "B. Melting", "C. Condensation", "D. Freezing"], "answer": "C"},
    {"question": "What is the process of a liquid turning into a gas called?", "options": ["A. Evaporation", "B. Melting", "C. Condensation", "D. Sublimation"], "answer": "A"},
    {"question": "What type of bond involves the sharing of electron pairs?", "options": ["A. Ionic Bond", "B. Covalent Bond", "C. Metallic Bond", "D. Hydrogen Bond"], "answer": "B"},
    {"question": "What type of bond involves the transfer of electrons?", "options": ["A. Ionic Bond", "B. Covalent Bond", "C. Metallic Bond", "D. Van der Waals Bond"], "answer": "A"},
    {"question": "What is the chemical name for rust?", "options": ["A. Iron Oxide", "B. Iron Sulfide", "C. Iron Carbonate", "D. Iron Nitrate"], "answer": "A"},
    {"question": "What is the chemical formula for methane?", "options": ["A. CH4", "B. C2H6", "C. C2H4", "D. C3H8"], "answer": "A"},
    {"question": "What is the chemical formula for ammonia?", "options": ["A. NH3", "B. NH4", "C. N2H4", "D. NH2"], "answer": "A"},
    {"question": "What is the chemical formula for sulfuric acid?", "options": ["A. H2SO3", "B. H2SO4", "C. HSO4", "D. H2S"], "answer": "B"},
    {"question": "What is the chemical formula for hydrochloric acid?", "options": ["A. HCl", "B. HClO", "C. HClO2", "D. H2Cl"], "answer": "A"},
    {"question": "What is the chemical formula for glucose?", "options": ["A. C6H12O6", "B. C6H6O6", "C. C12H22O11", "D. C5H10O5"], "answer": "A"},
    {"question": "What are elements in the same column of the periodic table called?", "options": ["A. Periods", "B. Groups", "C. Series", "D. Blocks"], "answer": "B"},
    {"question": "What are elements in the same row of the periodic table called?", "options": ["A. Periods", "B. Groups", "C. Series", "D. Blocks"], "answer": "A"},
    {"question": "Which element is known as the 'King of Chemicals'?", "options": ["A. Nitric Acid", "B. Sulfuric Acid", "C. Hydrochloric Acid", "D. Acetic Acid"], "answer": "B"},
    {"question": "What is the number of protons in an atom called?", "options": ["A. Mass Number", "B. Atomic Number", "C. Neutron Number", "D. Isotope Number"], "answer": "B"},
    {"question": "What is the sum of protons and neutrons in an atom called?", "options": ["A. Atomic Number", "B. Mass Number", "C. Electron Number", "D. Valency"], "answer": "B"},
    {"question": "What are atoms of the same element with different numbers of neutrons called?", "options": ["A. Isomers", "B. Isotopes", "C. Isobars", "D. Ions"], "answer": "B"},
    {"question": "What is the term for a positively charged ion?", "options": ["A. Cation", "B. Anion", "C. Isotope", "D. Isomer"], "answer": "A"},
    {"question": "What is the term for a negatively charged ion?", "options": ["A. Cation", "B. Anion", "C. Isotope", "D. Isomer"], "answer": "B"},
    {"question": "Which gas is essential for combustion?", "options": ["A. Nitrogen", "B. Oxygen", "C. Hydrogen", "D. Carbon Dioxide"], "answer": "B"},
    {"question": "What is the chemical name for baking soda?", "options": ["A. Sodium Bicarbonate", "B. Sodium Chloride", "C. Sodium Carbonate", "D. Sodium Hydroxide"], "answer": "A"},
    {"question": "What is the chemical name for common salt?", "options": ["A. Sodium Bicarbonate", "B. Sodium Chloride", "C. Sodium Carbonate", "D. Sodium Sulfate"], "answer": "B"},
    {"question": "What catalyst is present in the human body that speeds up reactions?", "options": ["A. Hormones", "B. Enzymes", "C. Vitamins", "D. Proteins"], "answer": "B"},
    {"question": "Which noble gas is used in balloons due to its low density?", "options": ["A. Neon", "B. Argon", "C. Helium", "D. Krypton"], "answer": "C"},
    {"question": "What is the SI unit of amount of substance?", "options": ["A. Gram", "B. Mole", "C. Liter", "D. Kilogram"], "answer": "B"},
    {"question": "Who proposed the atomic theory of matter?", "options": ["A. John Dalton", "B. Niels Bohr", "C. Ernest Rutherford", "D. J.J. Thomson"], "answer": "A"},
]
