# /used ai for this

maths_questions = [
    {"question": "What is the value of Pi (π) approximately?", "options": ["A. 3.14", "B. 2.14", "C. 4.14", "D. 1.14"], "answer": "A"},
    {"question": "What is the sum of angles in a triangle?", "options": ["A. 90°", "B. 180°", "C. 270°", "D. 360°"], "answer": "B"},
    {"question": "What is the sum of angles in a quadrilateral?", "options": ["A. 180°", "B. 270°", "C. 360°", "D. 450°"], "answer": "C"},
    {"question": "What is the formula for the area of a circle?", "options": ["A. πr", "B. πr²", "C. 2πr", "D. πd"], "answer": "B"},
    {"question": "What is the formula for the circumference of a circle?", "options": ["A. πr", "B. πr²", "C. 2πr", "D. r²"], "answer": "C"},
    {"question": "What is the formula for the area of a rectangle?", "options": ["A. l + b", "B. l × b", "C. 2(l+b)", "D. l/b"], "answer": "B"},
    {"question": "What is the formula for the perimeter of a rectangle?", "options": ["A. l × b", "B. 2(l+b)", "C. l + b", "D. l²+b²"], "answer": "B"},
    {"question": "What is the formula for the area of a triangle?", "options": ["A. base × height", "B. 1/2 × base × height", "C. 2 × base × height", "D. base + height"], "answer": "B"},
    {"question": "What is the value of the square root of 144?", "options": ["A. 10", "B. 11", "C. 12", "D. 13"], "answer": "C"},
    {"question": "What is 7 factorial (7!)?", "options": ["A. 5040", "B. 720", "C. 4030", "D. 2520"], "answer": "A"},
    {"question": "What is the value of 2^10?", "options": ["A. 512", "B. 1024", "C. 2048", "D. 256"], "answer": "B"},
    {"question": "What is the Pythagorean theorem formula?", "options": ["A. a² + b² = c²", "B. a + b = c", "C. a² - b² = c²", "D. a × b = c²"], "answer": "A"},
    {"question": "What is the value of sin 90°?", "options": ["A. 0", "B. 1", "C. -1", "D. 0.5"], "answer": "B"},
    {"question": "What is the value of cos 0°?", "options": ["A. 0", "B. 1", "C. -1", "D. 0.5"], "answer": "B"},
    {"question": "What is the value of tan 45°?", "options": ["A. 0", "B. 1", "C. -1", "D. 0.5"], "answer": "B"},
    {"question": "What is a prime number?", "options": ["A. A number divisible by 1 only", "B. A number divisible by 1 and itself only", "C. An even number", "D. An odd number"], "answer": "B"},
    {"question": "Which of the following is a prime number?", "options": ["A. 9", "B. 15", "C. 17", "D. 21"], "answer": "C"},
    {"question": "What is the smallest prime number?", "options": ["A. 0", "B. 1", "C. 2", "D. 3"], "answer": "C"},
    {"question": "What is the LCM of 4 and 6?", "options": ["A. 10", "B. 12", "C. 24", "D. 8"], "answer": "B"},
    {"question": "What is the HCF of 12 and 18?", "options": ["A. 2", "B. 3", "C. 6", "D. 9"], "answer": "C"},
    {"question": "What is the value of 0 factorial (0!)?", "options": ["A. 0", "B. 1", "C. Undefined", "D. -1"], "answer": "B"},
    {"question": "What is the sum of the first 10 natural numbers?", "options": ["A. 45", "B. 50", "C. 55", "D. 60"], "answer": "C"},
    {"question": "What is the formula for the volume of a cube?", "options": ["A. a²", "B. a³", "C. 6a²", "D. 4a"], "answer": "B"},
    {"question": "What is the formula for the volume of a sphere?", "options": ["A. 4/3 πr³", "B. πr²h", "C. 4πr²", "D. 2/3 πr³"], "answer": "A"},
    {"question": "What is the formula for the volume of a cylinder?", "options": ["A. πr²h", "B. 2πrh", "C. 4/3 πr³", "D. πr²"], "answer": "A"},
    {"question": "What is the value of log 1 (base 10)?", "options": ["A. 0", "B. 1", "C. 10", "D. Undefined"], "answer": "A"},
    {"question": "What type of number cannot be expressed as a fraction?", "options": ["A. Rational", "B. Irrational", "C. Whole", "D. Natural"], "answer": "B"},
    {"question": "What is an example of an irrational number?", "options": ["A. 1/2", "B. 0.5", "C. √2", "D. 4"], "answer": "C"},
    {"question": "What is the median of the numbers 3, 7, 9, 15, 20?", "options": ["A. 7", "B. 9", "C. 15", "D. 20"], "answer": "B"},
    {"question": "What is the mode of the numbers 2, 3, 3, 5, 7?", "options": ["A. 2", "B. 3", "C. 5", "D. 7"], "answer": "B"},
    {"question": "What is the mean of 4, 8, 12, 16?", "options": ["A. 8", "B. 10", "C. 12", "D. 14"], "answer": "B"},
    {"question": "What is the value of x in 2x + 3 = 11?", "options": ["A. 3", "B. 4", "C. 5", "D. 6"], "answer": "B"},
    {"question": "What is the degree of a linear equation?", "options": ["A. 0", "B. 1", "C. 2", "D. 3"], "answer": "B"},
    {"question": "What is the degree of a quadratic equation?", "options": ["A. 1", "B. 2", "C. 3", "D. 4"], "answer": "B"},
    {"question": "What is the standard form of a quadratic equation?", "options": ["A. ax + b = 0", "B. ax² + bx + c = 0", "C. ax³ + bx² = 0", "D. a/x = 0"], "answer": "B"},
    {"question": "What is the discriminant formula in a quadratic equation?", "options": ["A. b² - 4ac", "B. b² + 4ac", "C. 4ac - b²", "D. b² - 2ac"], "answer": "A"},
    {"question": "How many sides does a hexagon have?", "options": ["A. 5", "B. 6", "C. 7", "D. 8"], "answer": "B"},
    {"question": "How many sides does a pentagon have?", "options": ["A. 4", "B. 5", "C. 6", "D. 7"], "answer": "B"},
    {"question": "How many sides does an octagon have?", "options": ["A. 6", "B. 7", "C. 8", "D. 9"], "answer": "C"},
    {"question": "What is the sum of interior angles of a hexagon?", "options": ["A. 540°", "B. 720°", "C. 900°", "D. 360°"], "answer": "B"},
    {"question": "What is a number raised to the power of 0 equal to?", "options": ["A. 0", "B. 1", "C. The number itself", "D. Undefined"], "answer": "B"},
    {"question": "What is the reciprocal of 5?", "options": ["A. 5", "B. -5", "C. 1/5", "D. 0"], "answer": "C"},
    {"question": "What is the value of i² in complex numbers (i = √-1)?", "options": ["A. 1", "B. -1", "C. 0", "D. i"], "answer": "B"},
    {"question": "What is the slope-intercept form of a line?", "options": ["A. y = mx + c", "B. ax + by = c", "C. y² = mx", "D. x = my + c"], "answer": "A"},
    {"question": "What does 'congruent' mean in geometry?", "options": ["A. Same shape only", "B. Same size only", "C. Same shape and size", "D. Same angle only"], "answer": "C"},
    {"question": "What is the value of 5C2 (Combination)?", "options": ["A. 5", "B. 10", "C. 15", "D. 20"], "answer": "B"},
    {"question": "What is the value of 5P2 (Permutation)?", "options": ["A. 10", "B. 15", "C. 20", "D. 25"], "answer": "C"},
    {"question": "What is the probability of getting a head in a single coin toss?", "options": ["A. 0", "B. 1/4", "C. 1/2", "D. 1"], "answer": "C"},
    {"question": "What is the probability of getting a 6 on a single die roll?", "options": ["A. 1/2", "B. 1/3", "C. 1/6", "D. 1"], "answer": "C"},
    {"question": "What is the sum of the interior angles of any polygon with n sides?", "options": ["A. (n-2) × 180°", "B. n × 180°", "C. (n+2) × 180°", "D. n × 90°"], "answer": "A"},
]

