# /used ai for this

physics_questions = [
    {"question": "What is the SI unit of Force?", "options": ["A. Newton", "B. Joule", "C. Watt", "D. Pascal"], "answer": "A"},
    {"question": "What is the SI unit of Energy?", "options": ["A. Newton", "B. Joule", "C. Watt", "D. Pascal"], "answer": "B"},
    {"question": "What is the SI unit of Power?", "options": ["A. Newton", "B. Joule", "C. Watt", "D. Pascal"], "answer": "C"},
    {"question": "What is the SI unit of Pressure?", "options": ["A. Newton", "B. Joule", "C. Watt", "D. Pascal"], "answer": "D"},
    {"question": "What is the SI unit of Electric Current?", "options": ["A. Volt", "B. Ampere", "C. Ohm", "D. Watt"], "answer": "B"},
    {"question": "What is the SI unit of Electric Resistance?", "options": ["A. Volt", "B. Ampere", "C. Ohm", "D. Farad"], "answer": "C"},
    {"question": "What is the SI unit of Frequency?", "options": ["A. Hertz", "B. Newton", "C. Joule", "D. Tesla"], "answer": "A"},
    {"question": "What is the SI unit of Temperature?", "options": ["A. Celsius", "B. Fahrenheit", "C. Kelvin", "D. Joule"], "answer": "C"},
    {"question": "What is the SI unit of Mass?", "options": ["A. Gram", "B. Kilogram", "C. Pound", "D. Ton"], "answer": "B"},
    {"question": "What is the SI unit of Length?", "options": ["A. Centimeter", "B. Inch", "C. Meter", "D. Foot"], "answer": "C"},
    {"question": "What is the SI unit of Time?", "options": ["A. Minute", "B. Hour", "C. Second", "D. Day"], "answer": "C"},
    {"question": "What is the SI unit of Electric Charge?", "options": ["A. Coulomb", "B. Ampere", "C. Volt", "D. Farad"], "answer": "A"},
    {"question": "What is the SI unit of Magnetic Field?", "options": ["A. Weber", "B. Tesla", "C. Henry", "D. Gauss"], "answer": "B"},
    {"question": "What is the SI unit of Capacitance?", "options": ["A. Farad", "B. Henry", "C. Ohm", "D. Weber"], "answer": "A"},
    {"question": "What is the SI unit of Inductance?", "options": ["A. Farad", "B. Henry", "C. Ohm", "D. Weber"], "answer": "B"},
    {"question": "What is the SI unit of Luminous Intensity?", "options": ["A. Lux", "B. Lumen", "C. Candela", "D. Watt"], "answer": "C"},
    {"question": "What is the SI unit of Amount of Substance?", "options": ["A. Mole", "B. Gram", "C. Liter", "D. Kilogram"], "answer": "A"},
    {"question": "What is the formula for Kinetic Energy?", "options": ["A. mgh", "B. 1/2 mv²", "C. mv", "D. Fd"], "answer": "B"},
    {"question": "What is the formula for Potential Energy?", "options": ["A. mgh", "B. 1/2 mv²", "C. mv", "D. Fd"], "answer": "A"},
    {"question": "Newton's First Law is also known as?", "options": ["A. Law of Inertia", "B. Law of Acceleration", "C. Law of Action-Reaction", "D. Law of Gravitation"], "answer": "A"},
    {"question": "Newton's Second Law relates Force to?", "options": ["A. Mass and Velocity", "B. Mass and Acceleration", "C. Velocity and Time", "D. Distance and Time"], "answer": "B"},
    {"question": "Newton's Third Law states?", "options": ["A. Every action has an equal and opposite reaction", "B. Objects at rest stay at rest", "C. Force equals mass times acceleration", "D. Energy cannot be created or destroyed"], "answer": "A"},
    {"question": "What is the acceleration due to gravity on Earth (approx)?", "options": ["A. 8.8 m/s²", "B. 9.8 m/s²", "C. 10.8 m/s²", "D. 11.8 m/s²"], "answer": "B"},
    {"question": "Which law states that energy cannot be created or destroyed?", "options": ["A. Law of Conservation of Momentum", "B. Law of Conservation of Energy", "C. Law of Gravitation", "D. Law of Thermodynamics"], "answer": "B"},
    {"question": "What is the speed of light in vacuum?", "options": ["A. 3 x 10^8 m/s", "B. 3 x 10^6 m/s", "C. 3 x 10^10 m/s", "D. 3 x 10^5 m/s"], "answer": "A"},
    {"question": "Who proposed the theory of relativity?", "options": ["A. Isaac Newton", "B. Albert Einstein", "C. Niels Bohr", "D. Max Planck"], "answer": "B"},
    {"question": "What is the unit of Work?", "options": ["A. Newton", "B. Joule", "C. Watt", "D. Pascal"], "answer": "B"},
    {"question": "What type of lens is used to correct myopia?", "options": ["A. Convex", "B. Concave", "C. Cylindrical", "D. Bifocal"], "answer": "B"},
    {"question": "What type of lens is used to correct hypermetropia?", "options": ["A. Convex", "B. Concave", "C. Cylindrical", "D. Bifocal"], "answer": "A"},
    {"question": "What is the phenomenon of splitting white light into colors called?", "options": ["A. Reflection", "B. Refraction", "C. Dispersion", "D. Diffraction"], "answer": "C"},
    {"question": "What is the bending of light when it passes from one medium to another called?", "options": ["A. Reflection", "B. Refraction", "C. Dispersion", "D. Diffraction"], "answer": "B"},
    {"question": "What device is used to measure atmospheric pressure?", "options": ["A. Thermometer", "B. Barometer", "C. Hygrometer", "D. Manometer"], "answer": "B"},
    {"question": "What device is used to measure electric current?", "options": ["A. Voltmeter", "B. Ammeter", "C. Ohmmeter", "D. Galvanometer"], "answer": "B"},
    {"question": "What device is used to measure voltage?", "options": ["A. Voltmeter", "B. Ammeter", "C. Ohmmeter", "D. Wattmeter"], "answer": "A"},
    {"question": "Sound cannot travel through which medium?", "options": ["A. Solid", "B. Liquid", "C. Gas", "D. Vacuum"], "answer": "D"},
    {"question": "What is the unit used to measure the loudness of sound?", "options": ["A. Hertz", "B. Decibel", "C. Watt", "D. Joule"], "answer": "B"},
    {"question": "The study of motion without considering forces is called?", "options": ["A. Dynamics", "B. Kinematics", "C. Statics", "D. Mechanics"], "answer": "B"},
    {"question": "The study of motion considering forces is called?", "options": ["A. Dynamics", "B. Kinematics", "C. Statics", "D. Optics"], "answer": "A"},
    {"question": "What is the SI unit of Momentum?", "options": ["A. kg m/s", "B. kg m/s²", "C. N", "D. J"], "answer": "A"},
    {"question": "What is the value of 1 Horsepower approximately in Watts?", "options": ["A. 746 W", "B. 550 W", "C. 1000 W", "D. 100 W"], "answer": "A"},
    {"question": "What causes a rainbow?", "options": ["A. Reflection only", "B. Refraction only", "C. Refraction and dispersion of light", "D. Diffraction only"], "answer": "C"},
    {"question": "Which particle has a negative charge?", "options": ["A. Proton", "B. Neutron", "C. Electron", "D. Positron"], "answer": "C"},
    {"question": "Which particle has no charge?", "options": ["A. Proton", "B. Neutron", "C. Electron", "D. Positron"], "answer": "B"},
    {"question": "What is the process of converting a solid directly into gas called?", "options": ["A. Evaporation", "B. Condensation", "C. Sublimation", "D. Fusion"], "answer": "C"},
    {"question": "What is the term for the resistance of a body to change its state of motion?", "options": ["A. Momentum", "B. Inertia", "C. Velocity", "D. Acceleration"], "answer": "B"},
    {"question": "What is the escape velocity of Earth approximately?", "options": ["A. 7.9 km/s", "B. 9.8 km/s", "C. 11.2 km/s", "D. 15.0 km/s"], "answer": "C"},
    {"question": "Who discovered the law of gravitation?", "options": ["A. Albert Einstein", "B. Isaac Newton", "C. Galileo Galilei", "D. Johannes Kepler"], "answer": "B"},
    {"question": "What is the unit for measuring radioactivity?", "options": ["A. Becquerel", "B. Curie", "C. Sievert", "D. Both A and B"], "answer": "D"},
    {"question": "What is the phenomenon where light bounces back from a surface called?", "options": ["A. Refraction", "B. Reflection", "C. Diffraction", "D. Dispersion"], "answer": "B"},
    {"question": "Which scientist formulated the three laws of planetary motion?", "options": ["A. Newton", "B. Kepler", "C. Galileo", "D. Copernicus"], "answer": "B"},
]
